import { Country } from '../types';

export const PHONE_COUNTRY_FORMATS: Record<Country, string> = {
  poland: 'AAA-AAA-AAA',
  ukraine: 'AA AAA AA AA',
  'united-kingdom': 'AAAA AAAAA',
  'united-arab-emirates': 'AA AAA-AAA',
  'united-states-of-america': 'AAA-AAA-AAAA',
  argentina: 'A AAA AAA-AAAA',
  australia: 'A AAA AAA AAA',
  austria: 'AAAA AAAAA',
  belgium: 'AA AA AA AA',
  brazil: 'AA AAAA AAAA',
  canada: 'AAA-AAAA-AAAA',
  finland: 'AA AAA AA AA',
  hungary: 'AA AAA AAA',
  ireland: 'A AAA AAAA',
  italy: 'AAA AAA AAAA',
  latvia: 'AAAA AAAA',
  scotland: 'AAA AAA AAAA',
  sweden: 'AAA-AAAA-AAA',
  taiwan: 'A-AAAA-AAAA',
  germany: 'AA AAAAAA',
  france: 'A AA AA AA AA',
};
